In [1]:
import tensorflow as tf

tensor1 = tf.constant(value = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
tensor2 = tf.constant(value = [20, 21, 22, 23])

tf.print(tensor1.shape)
tf.print(tensor2.shape)

dataset = tf.data.Dataset.from_tensor_slices((tensor1, tensor2))

print('\nOriginal dataset')
for i in dataset:
      tf.print(i)

dataset = dataset.repeat(3)

print('\nRepeated dataset')
for i in dataset:
      tf.print(i)

dataset = dataset.shuffle(3)

print('\nShuffled dataset')
for i in dataset:
      tf.print(i)

dataset = dataset.batch(2)

print('\n*******************')
print('* Batched dataset * ')
print('*******************')
for i in dataset:
      tf.print(i)

dataset = dataset.prefetch(1)

print('\nPrefetched dataset')
for i in dataset:
      tf.print(i)

print('\nDataset take')
for iter, (temp1, temp2) in enumerate(dataset.take(2), 1):
  print('Iteration number {}'.format(iter))
  tf.print('Features batch {}'.format(temp1))
  tf.print('Classes batch {}'.format(temp2))


TensorShape([4, 3])
TensorShape([4])

Original dataset
([1 2 3], 20)
([4 5 6], 21)
([7 8 9], 22)
([10 11 12], 23)

Repeated dataset
([1 2 3], 20)
([4 5 6], 21)
([7 8 9], 22)
([10 11 12], 23)
([1 2 3], 20)
([4 5 6], 21)
([7 8 9], 22)
([10 11 12], 23)
([1 2 3], 20)
([4 5 6], 21)
([7 8 9], 22)
([10 11 12], 23)

Shuffled dataset
([4 5 6], 21)
([10 11 12], 23)
([1 2 3], 20)
([1 2 3], 20)
([4 5 6], 21)
([7 8 9], 22)
([7 8 9], 22)
([4 5 6], 21)
([10 11 12], 23)
([10 11 12], 23)
([1 2 3], 20)
([7 8 9], 22)

*******************
* Batched dataset * 
*******************
([[4 5 6]
 [7 8 9]], [21 22])
([[1 2 3]
 [10 11 12]], [20 23])
([[1 2 3]
 [4 5 6]], [20 21])
([[7 8 9]
 [10 11 12]], [22 23])
([[1 2 3]
 [4 5 6]], [20 21])
([[7 8 9]
 [10 11 12]], [22 23])

Prefetched dataset
([[7 8 9]
 [4 5 6]], [22 21])
([[1 2 3]
 [4 5 6]], [20 21])
([[10 11 12]
 [1 2 3]], [23 20])
([[1 2 3]
 [10 11 12]], [20 23])
([[4 5 6]
 [10 11 12]], [21 23])
([[7 8 9]
 [7 8 9]], [22 22])

Dataset take
Iteration number 1
Fea