In [ ]:
#from __future__ import print_function
import tensorflow as tf

In [ ]:
# --- 1d constant tensors
instruments       = tf.constant(["Violin", "Piano"], tf.string)
rationalNumbers   = tf.constant([1.223, 2.131, -10.43], tf.float32)

print("`instruments` is a {}-d Tensor with shape: {}".format(tf.rank(instruments).numpy(), tf.shape(instruments)))
print("`rationalNumbers` is a {}-d Tensor with shape: {}".format(tf.rank(rationalNumbers).numpy(), tf.shape(rationalNumbers)))

`instruments` is a 1-d Tensor with shape: [2]
`rationalNumbers` is a 1-d Tensor with shape: [3]


In [ ]:
# --- N-dimensional constant tensors
images = tf.constant(tf.zeros((3, 128, 128, 16), tf.float64, "4d constant tensor definition"))

assert isinstance(images, tf.Tensor), "Matrix must be a TensorFlow tensor object"
assert tf.rank(images).numpy() == 4, "Matrix must be of rank 4"
assert tf.shape(images).numpy().tolist() == [3, 128, 128, 16], "Matrix has incorrect shape"

In [ ]:
threeDimensionalList = [[[0, 1, 2], 
                         [3, 4, 5]], 
                        [[6, 7, 8], 
                         [9, 10, 11]]]
rank3Tensor = tf.constant(threeDimensionalList)
print(rank3Tensor)
print("The number tensor dimensions is", rank3Tensor.ndim)
print("The tensor shape is", rank3Tensor.shape)
print("The tensor data type is", rank3Tensor.dtype)
print("The tensor size is", tf.size(rank3Tensor).numpy())

tf.Tensor(
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]], shape=(2, 2, 3), dtype=int32)
The number tensor dimensions is 3
The tensor shape is (2, 2, 3)
The tensor data type is <dtype: 'int32'>
The tensor size is 12


In [ ]:
# --- Indexing
aList = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
aTensor = tf.constant(aList)

print("The first element is:", aTensor[0].numpy())
print("The last element is:", aTensor[-1].numpy())
print("Elements in between the first and the last:", aTensor[1 : -1].numpy())

The first element is: 0
The last element is: 11
Elements in between the first and the last: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# --- Basic operations
a = tf.constant([[3, 2], [-10, 7]], dtype=tf.float32)
b = tf.constant([[0, 2], [  6, 1]], dtype=tf.float32)

addingTensors         = tf.add(a, b)
multiplyingTensors    = tf.multiply(a, b)
matrixMultiplication  = tf.matmul(a, b)
tf.print(addingTensors)
tf.print(multiplyingTensors)
tf.print(matrixMultiplication)

print("The maximum value of b is:", tf.reduce_max(b).numpy())
print("The index position of the maximum element of b is:", tf.argmax(b).numpy())

[[3 4]
 [-4 8]]
[[0 4]
 [-60 7]]
[[12 8]
 [42 -13]]
The maximum value of b is: 6.0
The index position of the maximum element of b is: [1 0]


In [ ]:
a = tf.constant([[1, 2, 3, 4, 5, 6]])
print('Initial shape:', a.shape)

b = tf.reshape(a, [6, 1])
print('First reshaping:', b.shape)

c = tf.reshape(a, [3, 2])
print('Second reshaping:', c.shape)

# --- Flattening
print('Flattening:', tf.reshape(a, [-1]))

Initial shape: (1, 6)
First reshaping: (6, 1)
Second reshaping: (3, 2)
Flattening: tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [ ]:
# --- Operator overload
m = tf.constant([5])

n = tf.constant([[1, 2], [3, 4]])

tf.print(tf.multiply(m, n))

[[5 10]
 [15 20]]


In [ ]:
# --- Ragged tensors
raggedList = [[1, 2, 3], [4, 5], [6]]

raggedTensor = tf.ragged.constant(raggedList)

tf.print(raggedTensor)

[[1, 2, 3], [4, 5], [6]]


In [ ]:
# --- String tensors
stringTensor = tf.constant(["I like", 
                            "TensorFlow", 
                            "very much"])

tf.print(stringTensor)

["I like" "TensorFlow" "very much"]


In [ ]:
# --- Sparse tensors
sparseTensor = tf.sparse.SparseTensor(indices      = [[0, 0], [2, 2], [4, 4]], 
                                      values       = [25, 50, 100], 
                                      dense_shape  = [5, 5])

tf.print(sparseTensor)
tf.print(tf.sparse.to_dense(sparseTensor))

'SparseTensor(indices=[[0 0]
 [2 2]
 [4 4]], values=[25 50 100], shape=[5 5])'
[[25 0 0 0 0]
 [0 0 0 0 0]
 [0 0 50 0 0]
 [0 0 0 0 0]
 [0 0 0 0 100]]


In [ ]:
constantA = tf.constant([[0.0, 1.0],
                         [2.0, 3.0]])
variableA = tf.Variable(constantA, name = "variableAName")
tf.print(variableA)

variableB = tf.Variable(1000)
tf.print(variableB)

listC = [[0.0, 1.0],
         [2.0, 3.0]]
variableC = tf.Variable(listC)
tf.print(variableC)

variableD = tf.Variable("Sample string")
tf.print(variableD)

stringListE = ["I like", "TensorFlow", "very much"]
variableE   = tf.Variable(stringListE)
tf.print(variableE)

[[0 1]
 [2 3]]
1000
[[0 1]
 [2 3]]
Sample string
["I like" "TensorFlow" "very much"]


In [ ]:
print("Values stored in variableA: \n", variableA.value())
print("Values stored in variableA: \n", variableA.numpy())
tf.print("Values stored in variableA: \n", variableA.value())

print("Variable name: ", variableA.name)

print("Datatype of variableA: ", variableA.dtype)

print("Shape of variableA: ", variableA.shape)

print("Number of dimensions of variableA:", tf.rank(variableA).numpy())

print("Number of elements of variableA:", tf.size(variableA).numpy())

Values stored in variableA: 
 tf.Tensor(
[[0. 1.]
 [2. 3.]], shape=(2, 2), dtype=float32)
Values stored in variableA: 
 [[0. 1.]
 [2. 3.]]
Values stored in variableA: 
 [[0 1]
 [2 3]]
Variable name:  variableAName:0
Datatype of variableA:  <dtype: 'float32'>
Shape of variableA:  (2, 2)
Number of dimensions of variableA: 2
Number of elements of variableA: 4


In [ ]:
a = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

tf.print("Addition by 2:\n", a + 2)
tf.print("Substraction by 2:\n", a - 2)
tf.print("Multiplication by 2:\n", a * 2)
tf.print("Division by 2:\n", a / 2)
tf.print("Matmul operation with itself:\n", a @ a)
tf.print("Modulo operation by 2:\n", a % 2)

a.assign(([[3, 20], [-2, 110]]))
tf.print(a)

print("The 1st element of the first level is:", a[0].numpy())
print("The 2nd element of the first level is:", a[1].numpy())
print("The 1st element of the second level is:", a[0, 0].numpy())
print("The 3rd element of the second level is:", a[0, 1].numpy())

Addition by 2:
 [[3 4]
 [5 6]]
Substraction by 2:
 [[-1 0]
 [1 2]]
Multiplication by 2:
 [[2 4]
 [6 8]]
Division by 2:
 [[0.5 1]
 [1.5 2]]
Matmul operation with itself:
 [[7 10]
 [15 22]]
Modulo operation by 2:
 [[1 0]
 [1 0]]
[[3 20]
 [-2 110]]
The 1st element of the first level is: [ 3. 20.]
The 2nd element of the first level is: [ -2. 110.]
The 1st element of the second level is: 3.0
The 3rd element of the second level is: 20.0


In [ ]:
b = tf.Variable([5])
c = tf.Variable([[1, 2], [3, 4]])
tf.print(b * c)

[[5 10]
 [15 20]]


In [ ]:
a = tf.Variable([[1.0, 2.0], [1.0, 2.0]])

tf.print(tf.reshape(a, (4, 1)))

[[1]
 [2]
 [1]
 [2]]


In [ ]:
print("Device processing variable a:\n", a.device)

with tf.device('CPU:0'):
  a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  b = tf.Variable([[1.0, 2.0, 3.0]])
  print("Device processing variable a:\n", a.device)
  print("Device processing variable b:\n", b.device)

with tf.device('GPU:0'):
  # Element-wise multiply
  k = a * b
  print("Device processing the calculation:\n", k.device)

Device processing variable a:
 /job:localhost/replica:0/task:0/device:GPU:0
Device processing variable a:
 /job:localhost/replica:0/task:0/device:CPU:0
Device processing variable b:
 /job:localhost/replica:0/task:0/device:CPU:0
Device processing the calculation:
 /job:localhost/replica:0/task:0/device:GPU:0


In [ ]:
tf.print(rationalNumbers)
rationalNumbers = tf.add(rationalNumbers, rationalNumbers)
tf.print(rationalNumbers)

In [ ]:
a = tf.constant(2)
a = a + 1

tf.print(a)

3
